# Generated by Django 5.0.6 on 2024-06-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
