# Generated by Django 5.0.6 on 2024-06-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_comment_alter_blog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
